### ISSUE TITLE
How to get rid of placing each element in brackets placing in new line?

### ISSUE THREAD

**Issue by alex-shamshurin** [maksimr/vim-jsbeautify#132]
See this 
![formatting_issues](https://cloud.githubusercontent.com/assets/1595209/23100646/957b78f0-f697-11e6-8825-6fc5efb9a603.jpg)

**Comment by maksimr** [comment]
@alex-shamshurin looks like a problem in [js-beautify](https://github.com/beautify-web/js-beautify).

Because most of a formatting stuff handled by this lib

Thanks

**Comment by alex-shamshurin** [comment]
Yes, I know, but may be there is a way to improve result a bit? This is a beautifier, not uglifier, ist't it?

**Comment by alex-shamshurin** [comment]
May me switch to [jscs](http://jscs.info/) as a backend lib?

**Comment by maksimr** [comment]
@alex-shamshurin 

> but may be there is a way to improve result a bit

I think yes, but the best first place for a question about formatting is [js-beautify](https://github.com/beautify-web/js-beautify) because the current plugin does not format your code it only take code from your file, take options from editor config and pass it to js-beautify lib.


> May me switch to jscs as a backend lib?

Pull request are welcome :)

**Comment by alex-shamshurin** [comment]
Unfornutely I dot know VIM script, but I'd like to have everything working, This is my [issue ](jsctags https://github.com/ramitos/jsctags/issues/50)  about tags and linting. May be it will be interesting for you and you could give me an advise.
